package net.arsentic.arsenticskyblock.configs

import net.arsentic.arsenticskyblock.IridiumSkyblock
import net.arsentic.arsenticskyblock.commands.*

class Commands(plugin: IridiumSkyblock) {
    var createCommand = CreateCommand(plugin)
    var homeCommand = HomeCommand(plugin)
    var deleteCommand = DeleteCommand(plugin)
    var reloadCommand = ReloadCommand(plugin)
    var regenCommand = RegenCommand(plugin)
    var inviteCommand = InviteCommand(plugin)
    var joinCommand = JoinCommand(plugin)
    var missionsCommand = MissionsCommand(plugin)
    var upgradeCommand = UpgradeCommand(plugin)
    var boosterCommand = BoosterCommand(plugin)
    var crystalsCommand = CrystalsCommand(plugin)
    var giveCrystalsCommand = GiveCrystalsCommand(plugin)
    var removeCrystalsCommand = RemoveCrystalsCommand(plugin)
    var membersCommand = MembersCommand(plugin)
    var flyCommand = FlyCommand(plugin)
    var aboutCommand = AboutCommand(plugin)
    var warpsCommand = WarpsCommand(plugin)
    var warpCommand = SetWarpCommand(plugin)
    var valueCommand = ValueCommand(plugin)
    var topCommand = TopCommand(plugin)
    var leaveCommand = LeaveCommand(plugin)
    var worldBorderCommand = WorldBorderCommand(plugin)
    var kickCommand = KickCommand(plugin)
    var visitCommand = VisitCommand(plugin)
    var publicCommand = PublicCommand(plugin)
    var privateCommand = PrivateCommand(plugin)
    var bypassCommand = BypassCommand(plugin)
    var setHomeCommand = SetHomeCommand(plugin)
    var permissionsCommand = PermissionsCommand(plugin)
    var transferCommand = TransferCommand(plugin)
    var adminCommand = AdminCommand(plugin)
    var giveBoosterCommand = GiveBoosterCommand(plugin)
    var giveUpgradeCommand = GiveUpgradeCommand(plugin)
    var banCommand = BanCommand(plugin)
    var unBanCommand = UnBanCommand(plugin)
    var coopCommand = CoopCommand(plugin)
    var unCoopCommand = UnCoopCommand(plugin)
    var setNameCommand = SetNameCommand(plugin)
    var bankCommand = BankCommand(plugin)
    var chatCommand = ChatCommand(plugin)
    var shopCommand = ShopCommand(plugin)
    var biomeCommand = BiomeCommand(plugin)
    var helpCommand = HelpCommand(plugin)
    var languagesCommand = LanguagesCommand(plugin)
    var recalculateCommand = RecalculateCommand(plugin)
    var addValueCommand = AddValueCommand(plugin)
    var removeValueCommand = RemoveValueCommand(plugin)
}